#ifndef LANG_H
#define LANG_H

// Language selection definitions
#define LANGUAGE_CHINESE 0
#define LANGUAGE_ENGLISH 1

// Default language
extern int currentLanguage;

// Language switching function
void setLanguage(int lang);

// Text ID definitions
#define TXT_WIFI_CONFIG_SUCCESS 0
#define TXT_DEVICE_RESTART_NOTICE 1
#define TXT_WIFI_CONFIG_FAILED 2
#define TXT_MISSING_PARAMETERS 3
#define TXT_PID_SAVED 4
#define TXT_CONFIG_SAVE_FAILED 5
#define TXT_PID_ENABLED 6
#define TXT_PID_DISABLED 7
#define TXT_RECEIVED_SERIAL_COMMAND 8
#define TXT_DEVICE_STATUS_HEADER 9
#define TXT_TEMPERATURE 10
#define TXT_TARGET_TEMPERATURE 11
#define TXT_HEATING_STATUS 12
#define TXT_ON 13
#define TXT_OFF 14
#define TXT_WORK_MODE 15
#define TXT_OVEN_MODE 16
#define TXT_TOASTER_MODE 17
#define TXT_WIFI_STATUS 18
#define TXT_CONNECTED 19
#define TXT_DISCONNECTED 20
#define TXT_PID_CONTROL 21
#define TXT_ENABLED 22
#define TXT_DISABLED 23
#define TXT_KP 24
#define TXT_KI 25
#define TXT_KD 26
#define TXT_IP_ADDRESS 27
#define TXT_DEVICE_RESTARTING 28
#define TXT_TARGET_TEMP_SET 29
#define TXT_HEATING_ON 30
#define TXT_HEATING_OFF 31
#define TXT_TEMP_CALIBRATION_MODE 32
#define TXT_USE_WEB_INTERFACE 33
#define TXT_KP_SET 34
#define TXT_KI_SET 35
#define TXT_KD_SET 36
#define TXT_CONFIG_SAVED_EEPROM 37
#define TXT_CONFIG_LOAD_FAILED 38
#define TXT_RESET_TO_DEFAULT 39
#define TXT_START_PID_AUTOTUNE 40
#define TXT_UNKNOWN_COMMAND 41
#define TXT_FILESYSTEM_INIT_FAILED 42
#define TXT_FILESYSTEM_INIT_SUCCESS 43
#define TXT_WIFI_CONFIG_LOADED 44
#define TXT_SSID 45
#define TXT_WIFI_CONNECT_SUCCESS 46
#define TXT_WIFI_CONNECT_FAILED_CP 47
#define TXT_NO_VALID_WIFI_CONFIG 48
#define TXT_FS_UPDATE_REQUEST 49
#define TXT_FS_IMAGE_FOUND 50
#define TXT_FS_UPDATE_APPLY 51
#define TXT_WARNING_NO_FS_IMAGE 52
#define TXT_BAKING_COMPLETE 53
#define TXT_START_PID_TUNING 54
#define TXT_SAFE_ENVIRONMENT 55
#define TXT_TARGET_TEMP_SET_TO 56
#define TXT_WAITING_TEMP_STABLE 57
#define TXT_CURRENT_TEMP 58
#define TXT_FIND_CRITICAL_GAIN 59
#define TXT_INCREASE_KP 60
#define TXT_OSCILLATION_DETECTED 61
#define TXT_PID_TUNING_COMPLETE 62
#define TXT_RECOMMENDED_PARAMS 63
#define TXT_NEW_PARAMS_SAVED 64
#define TXT_NO_OSCILLATION 65
#define TXT_TUNING_END 66

// Newly added text ID definitions
#define TXT_WIFI_CONNECT_TIMEOUT 67
#define TXT_WIFI_CONNECTION_RESULT 68
#define TXT_DEVICE_DISCOVERY_HANDLER 69
#define TXT_OTA_UPDATE_SETUP 70
#define TXT_SMART_OVEN_WIFI_CONFIG_PAGE 71
#define TXT_WIFI_NETWORK_SETTINGS 72
#define TXT_PLEASE_SELECT_WIFI_NETWORK 73
#define TXT_NO_AVAILABLE_WIFI_NETWORKS 74
#define TXT_WIFI_SCAN_FAILED 75
#define TXT_WARNING_RESET_CONFIRMATION 76
#define TXT_RESETTING 77
#define TXT_RESET_SUCCESS_RESTARTING 78
#define TXT_FACTORY_RESET_FAILED 79
#define TXT_SMART_OVEN_CONTROLLER_WIFI_CONFIG 80
#define TXT_WIFI_NETWORK_NAME 81
#define TXT_WIFI_PASSWORD 82
#define TXT_ENTER_WIFI_PASSWORD 83
#define TXT_CLICK_TO_SEARCH_WIFI 84
#define TXT_CONNECT_WIFI 85
#define TXT_SCAN_WIFI_FAILED_RETRY 86
#define TXT_SCAN_FAILED_PLEASE_RETRY 87
#define TXT_SMART_OVEN_CONTROLLER_OTA_UPDATE 88
#define TXT_FIRMWARE_UPDATE_BIN_FILE 89
#define TXT_SYSTEM_CORE 90
#define TXT_UPDATE_MAIN_PROGRAM_DESCRIPTION 91
#define TXT_FILESYSTEM_UPDATE_BIN_FILE 92
#define TXT_INTERFACE_AND_DATA 93
#define TXT_UPDATE_FILESYSTEM_DESCRIPTION 94
#define TXT_IMPORTANT_NOTE_FIRMWARE_UPGRADE 95
#define TXT_SELECT_FIRMWARE_FILE 96
#define TXT_START_FIRMWARE_UPGRADE 97
#define TXT_UPLOAD_PROGRESS 98
#define TXT_FIRMWARE_UPGRADE_SUCCESS 99
#define TXT_UPGRADE_FAILED 100
#define TXT_FILESYSTEM_UPDATE 101
#define TXT_IMPORTANT_NOTE_FILESYSTEM_UPDATE 102
#define TXT_SELECT_FILESYSTEM_IMAGE 103
#define TXT_START_FILESYSTEM_UPDATE 104
#define TXT_FILESYSTEM_UPDATE_SUCCESS 105
#define TXT_UPDATE_FAILED 106
#define TXT_DEVICE_WILL_RESTART_IN_3_SECONDS 107
#define TXT_FIRMWARE_UPGRADE_SUCCESS_JS 108
#define TXT_UPGRADE_FAILED_JS 109
#define TXT_FILESYSTEM_UPDATE_SUCCESS_JS 110
#define TXT_UPDATE_FAILED_JS 111
#define TXT_LOGGED_OUT 112
#define TXT_PASSWORD_CHANGED_SUCCESSFULLY 113
#define TXT_PASSWORD_MIN_LENGTH_ERROR 114
#define TXT_MISSING_NEW_PASSWORD 115
#define TXT_TEMPERATURE_CALIBRATION_RESET 116
#define TXT_FILESYSTEM_UPDATE_HANDLER 117
#define TXT_RESTARTING_TO_APPLY_FILESYSTEM_UPDATE 118
#define TXT_FILE_UPLOAD_HANDLER_REDIGNED 119
#define TXT_UNSUPPORTED_FILE_TYPE 120
#define TXT_FILE_UPLOAD_STARTED 121
#define TXT_FILENAME 122
#define TXT_SSE_RESPONSE_STREAM_STARTED 123
#define TXT_RESPONSE_HEADER_CONTENT_TYPE 124
#define TXT_SENDING_PROGRESS_EVENT 125
#define TXT_BLOCK 126
#define TXT_WRITTEN 127
#define TXT_ACCUMULATED 128
#define TXT_ESTIMATED_SIZE 129
#define TXT_PROGRESS 130
#define TXT_FILE_UPLOAD_COMPLETED 131
#define TXT_FILE 132
#define TXT_SIZE 133
#define TXT_TOTAL_BLOCKS 134
#define TXT_FILESYSTEM_IMAGE_UPLOAD_COMPLETE 135
#define TXT_WARNING_FILE_VALIDATION_FAILED 136
#define TXT_FIRMWARE_UPLOAD_COMPLETE 137
#define TXT_FILE_UPLOAD_CANCELLED 138
#define TXT_STATIC_FILE_SERVICE_SETUP 139
#define TXT_BEEP_CONFIG_SAVED 140
#define TXT_BEEP_BAKING_STARTED 141
#define TXT_BEEP_BAKING_COMPLETED 142
#define TXT_BEEP_ERROR 143
#define TXT_RECEIVED_TCP_COMMAND 144
#define TXT_WEB_SERVER_HANDLER 145
#define TXT_SCANNING_AVAILABLE_WIFI_NETWORKS 146
#define TXT_WIFI_CONFIG_SAVED_SUCCESSFULLY 147
#define TXT_DEVICE_WILL_RESTART_IN_5_SECONDS 148
#define TXT_ACCESS_DEVICE_IP_IF_CONNECTED 149
#define TXT_RESTART_PROVISIONING_IF_FAILED 150
#define TXT_WIFI_CONFIG_SAVE_FAILED 151
#define TXT_INCOMPLETE_PARAMETERS 152
#define TXT_PID_CONTROL_API_HANDLER 153
#define TXT_RETURN_CURRENT_PID_PARAMS 154
#define TXT_SET_PID_PARAMS 155
#define TXT_PID_PARAMS_SAVED_ALT 156
#define TXT_CONFIG_SAVE_FAILED_ALT 157
#define TXT_PID_ENABLED_STATUS 158
#define TXT_PID_DISABLED_STATUS 159
#define TXT_SERIAL_COMMAND_HANDLER 160
#define TXT_DEVICE_STATUS_INFO 161
#define TXT_TEMPERATURE_LABEL 162
#define TXT_TARGET_TEMPERATURE_LABEL 163
#define TXT_HEATING_STATUS_LABEL 164
#define TXT_WORKING_MODE 165
#define TXT_OVEN_MODE_LABEL 166
#define TXT_TOASTER_MODE_LABEL 167
#define TXT_WIFI_STATUS_LABEL 168
#define TXT_WIFI_CONNECTED 169
#define TXT_WIFI_NOT_CONNECTED 170
#define TXT_PID_CONTROL_LABEL 171
#define TXT_ENABLED_LABEL 172
#define TXT_DISABLED_LABEL 173
#define TXT_EXECUTING_DEVICE_RESTART 174
#define TXT_HEATING_TURNED_ON 175
#define TXT_HEATING_TURNED_OFF 176
#define TXT_CALIBRATION_MODE 177
#define TXT_USE_WEB_INTERFACE_FOR_CALIBRATION 178
#define TXT_PID_ENABLED_ALT 179
#define TXT_PID_DISABLED_ALT 180
#define TXT_CONFIG_SAVED_TO_EEPROM 181
#define TXT_CONFIG_SAVE_FAILED_ALT2 182
#define TXT_CONFIG_LOADED_FROM_EEPROM 183

// 智能烤箱控制器固件注释文本ID
#define TXT_SMART_OVEN_CONTROLLER_FIRMWARE 207
#define TXT_FIRMWARE_VERSION 208
#define TXT_MAIN_FEATURES 209
#define TXT_HARDWARE_SUPPORT 210
#define TXT_HARDWARE_PIN_DEFINITIONS 211
#define TXT_SYSTEM_CONFIGURATION_PARAMETERS 212
#define TXT_GLOBAL_OBJECT_DEFINITIONS 213
#define TXT_SYSTEM_RUNTIME_VARIABLES 214
#define TXT_HARDWARE_STATUS_MONITORING 215
#define TXT_DEVICE_INFORMATION_DEFINITION 216
#define TXT_WIFI_CONFIGURATION_PARAMETERS 217
#define TXT_CAPTIVE_PORTAL_MODE_CONFIGURATION 218
#define TXT_FILE_SYSTEM_STATUS 219
#define TXT_TEMPERATURE_CONTROL_VARIABLES 220
#define TXT_PID_CONTROL_VARIABLES 221
#define TXT_PID_CALCULATION_INTERMEDIATE_VARIABLES 222
#define TXT_PWM_CONTROL_VARIABLES 223
#define TXT_NETWORK_COMMUNICATION_CONFIGURATION 224
#define TXT_TEMPERATURE_CALIBRATION_PARAMETER_CONFIGURATION 225
#define TXT_DEVICE_DISCOVERY_CONFIGURATION 226
#define TXT_LED_STATUS_CONTROL_AND_BLINK_MANAGEMENT 227
#define TXT_BAKING_COMPLETION_STATUS_MANAGEMENT 228
#define TXT_EEPROM_CONFIGURATION_MANAGEMENT_MODULE 229

// 新增的main.ino文本ID
#define TXT_EEPROM_READ_FAILED_RETRY 230
#define TXT_WARNING_TEMP_OFFSET_OUT_OF_RANGE 231
#define TXT_WARNING_TEMP_SCALE_OUT_OF_RANGE 232
#define TXT_SENSOR_COMMUNICATION_ERROR 233
#define TXT_RAW_DATA 234
#define TXT_USING_SAVED_WIFI_CONFIG 235
#define TXT_WIFI_CONNECT_STATUS 236
#define TXT_CONNECTION_TIME 238
#define TXT_WIFI_CONNECT_FAILURE_REASON 239
#define TXT_WIFI_CONNECT_STATUS_ALT 240
#define TXT_IP_ADDRESS_ALT 241
#define TXT_FAILURE_REASON 242
#define TXT_SCANNING_WIFI_NETWORKS 243
#define TXT_SELECT_WIFI_NETWORK 244
#define TXT_SCAN_WIFI_FAILED 246
#define TXT_DEVICE_ID 253
#define TXT_FIRMWARE_VERSION_LABEL 254
#define TXT_CURRENT_TEMPERATURE 255
#define TXT_RECEIVED_TCP_COMMAND 262
#define TXT_TEMPERATURE_LABEL 264
#define TXT_TARGET_TEMPERATURE_LABEL 265
// 新增的WiFi和系统状态文本ID
#define TXT_STOPPING_CAPTIVE_PORTAL 274
#define TXT_WIFI_CONFIG_MISSING_START_PORTAL 275
#define TXT_SSID_LABEL 276
#define TXT_PASSWORD_LENGTH_LABEL 277
#define TXT_WIFI_CONNECTION_STATUS 278
#define TXT_WIFI_IDLE_STATUS 279
#define TXT_WIFI_NO_SSID_AVAIL 280
#define TXT_WIFI_SCAN_COMPLETED 281
#define TXT_WIFI_CONNECT_FAILED_STATUS 282
#define TXT_WIFI_CONNECTION_LOST 283
#define TXT_WIFI_UNKNOWN_STATUS 284
#define TXT_WIFI_CONNECT_SUCCESS 285
#define TXT_SECONDS 286
#define TXT_WIFI_CONNECT_FAILED_START_PORTAL 287
#define TXT_WIFI_CONNECT_SUCCESS_EXCLAMATION 288
#define TXT_WIFI_CONFIG_MISSING 289
#define TXT_ATTEMPTING_WIFI_CONNECT 290
#define TXT_WIFI_CONNECTING 291

// 新增的OTA和文件系统文本ID
#define TXT_OTA_INTEGRATED_WITH_WEB_SERVER 292
#define TXT_OTA_UPDATE_PAGE_ADDRESS 293
#define TXT_REDIRECTING_TO_CONTROL_PANEL_NORMAL_MODE 294
#define TXT_DEVICE_STATUS 295
#define TXT_FIRMWARE_VERSION 296
#define TXT_UPTIME 297
#define TXT_MINUTES 298
#define TXT_FREE_MEMORY 299
#define TXT_START_FILESYSTEM_UPDATE 300
#define TXT_FILESYSTEM_IMAGE_NOT_FOUND_ERROR 301
#define TXT_CANNOT_OPEN_FILESYSTEM_IMAGE_ERROR 302
#define TXT_CANNOT_OPEN_FILESYSTEM_IMAGE 303
#define TXT_FILE_CREATION_FAILED 304
#define TXT_COMPLETE_EVENT_SENT 305

// 新增的蜂鸣器和TCP文本ID
#define TXT_CONFIG_SAVE_SUCCESS_BEEP 306
#define TXT_BAKING_START_BEEP 307
#define TXT_BAKING_COMPLETE_BEEP 308
#define TXT_ERROR_BEEP 309
#define TXT_TCP_CLIENT_CONNECTED 310

// 新增的WiFi配置文本ID
#define TXT_WIFI_CONFIG_SAVE_SUCCESS 311
#define TXT_DEVICE_WILL_RESTART 312
#define TXT_IF_CONNECT_SUCCESS 313
#define TXT_IF_CONNECT_FAIL 314
#define TXT_WIFI_CONFIG_SAVE_FAILED 315
#define TXT_PID_PARAMS_SAVED 316
#define TXT_PID_ENABLED 317
#define TXT_PID_DISABLED 318

// 新增的串口命令文本ID
#define TXT_WIFI_STATUS_SERIAL 319
#define TXT_HEATING_TURNED_ON 320
#define TXT_HEATING_TURNED_OFF 321
#define TXT_CONFIG_SAVED_TO_EEPROM 322
#define TXT_CONFIG_LOAD_FAILED 323
#define TXT_CONFIG_LOADED_FROM_EEPROM 324
#define TXT_RESET_TO_DEFAULT_CONFIG 325
#define TXT_START_PID_AUTOTUNE 326
#define TXT_BAKING_COMPLETE_NOTIFICATION_END 327
#define TXT_FILESYSTEM_INIT_FAILED 328
#define TXT_FILESYSTEM_INIT_SUCCESS 329
#define TXT_WIFI_CONFIG_LOAD_SUCCESS 330
#define TXT_NO_VALID_WIFI_CONFIG 331
#define TXT_FILESYSTEM_UPDATE_REQUEST 332
#define TXT_FILESYSTEM_IMAGE_FOUND 333
#define TXT_FILESYSTEM_UPDATE_APPLY 334

// 新增的PID自动调优文本ID
#define TXT_START_PID_AUTOTUNE_PROCESS 335
#define TXT_ENSURE_OVEN_EMPTY 336
#define TXT_WAITING_FOR_TEMP_STABILIZE 337
#define TXT_FINDING_CRITICAL_GAIN 338
#define TXT_INCREASING_KP 339
#define TXT_SUSTAINED_OSCILLATION_DETECTED 340
#define TXT_OSCILLATION_PERIOD 341
#define TXT_PID_AUTOTUNE_COMPLETE 342
#define TXT_RECOMMENDED_PARAMS 343
#define TXT_NEW_PARAMS_SAVED_TO_EEPROM 344
#define TXT_NO_SUSTAINED_OSCILLATION 345
#define TXT_PID_AUTOTUNE_FINISHED 346
#define TXT_PID_AUTOTUNE_CONFIRM_REQUIRED 347
#define TXT_PID_AUTOTUNE_SEND_CONFIRM 348
#define TXT_PID_AUTOTUNE_CONFIRMED 349
#define TXT_PID_AUTOTUNE_CONFIRM_TIMEOUT 350
#define TXT_PID_AUTOTUNE_HIGH_TEMP_ERROR 351

// 新增的UDP和网络发现文本ID
#define TXT_RECEIVED_UDP_PACKET 347
#define TXT_CONTENT_LABEL 348
#define TXT_RECEIVED_DISCOVERY_REQUEST 349
#define TXT_SENDING_DEVICE_INFO_RESPONSE 350
#define TXT_SENDING_BROADCAST_DISCOVERY 351

// 新增的未知命令文本ID
#define TXT_UNKNOWN_COMMAND 352

// 新增的WiFi相关常量
#define TXT_WIFI_DISCONNECTED 353
#define TXT_WIFI_CONNECTION_FAILURE_REASON 354
#define TXT_WIFI_UNKNOWN_ERROR 355

// 新增的OTA相关常量
#define TXT_OTA_UPDATE_PAGE_ADDRESS 356
#define TXT_WEB_SERVER_STARTED 359

#define TXT_PID_CONTROL_TEMP 270
#define TXT_TARGET 271
#define TXT_ERROR 272
#define TXT_PID_OUTPUT 273
// TXT_SENSOR_DATA_INVALID 已在前面定义 (值为326)
#define TXT_SENSOR_COMM_FAILURE 344
#define TXT_SENSOR_READ_FAILURE 345
#define TXT_TEMP_READ 346
#define TXT_TEMP_OUT_OF_RANGE 347
#define TXT_SENSOR_STATUS_ABNORMAL 348
#define TXT_SENSOR_STATUS_FAILURE 349
#define TXT_SENSOR_COMM_ERROR 350
#define TXT_TEMP_CALIBRATION_COMPLETE 351
#define TXT_ACTUAL_TEMP 352
#define TXT_MEASURED_TEMP 353
#define TXT_CALIBRATION_SAVED 354
#define TXT_CAPTIVE_PORTAL_START 355
#define TXT_AP_SSID 356
#define TXT_AP_IP 357
#define TXT_CAPTIVE_PORTAL_STARTED 358

// 新增的错误消息文本ID
#define TXT_ERROR_SSID_INVALID 322
#define TXT_ERROR_PASSWORD_TOO_LONG 323
#define TXT_EEPROM_SAVE_RETRY 324
#define TXT_CONFIG_SAVED_SUCCESS 325
  #define TXT_EEPROM_READ_FAILED 327
  #define TXT_EEPROM_SAVE_RETRY 324
  #define TXT_PASSWORD_LENGTH 331
  #define TXT_TEMP_OFFSET 332
  #define TXT_TEMP_SCALE 333
  #define TXT_PID_KP 334
  #define TXT_PID_ENABLED 335
  #define TXT_ENABLED 336
  #define TXT_DISABLED 337
#define TXT_LOADING_CONFIG 328
#define TXT_CONFIG_SIGNATURE 329
#define TXT_CONFIG_SSID 330
#define TXT_PASSWORD_LENGTH 331
#define TXT_TEMP_OFFSET 332
#define TXT_TEMP_SCALE 333
#define TXT_PID_KP 334
// TXT_PID_ENABLED 已在前面定义 (值为6)
// TXT_ENABLED 已在前面定义 (值为22)
// TXT_DISABLED 已在前面定义 (值为23)
#define TXT_CONFIG_LOAD_SUCCESS 338
#define TXT_CONFIG_SIGNATURE_INVALID 339
#define TXT_DEFAULT_CONFIG_LOADED 340
#define TXT_EEPROM_SAVE_FAILED 341
#define TXT_EEPROM_READ_RETRY 13
#define TXT_TEMP_CALIBRATION_OFFSET_WARN 14
#define TXT_READ_ATTEMPT 342
#define TXT_TEMP_CALIBRATION_SCALE_WARN 15
#define TXT_CONFIG_LOAD_FAILED_ALT 184
#define TXT_RESET_TO_DEFAULT_CONFIG 185
#define TXT_START_PID_AUTOTUNE_ALT 186
#define TXT_UNKNOWN_COMMAND_ALT 187
#define TXT_BAKING_COMPLETE_NOTIFICATION_END 188
#define TXT_FILESYSTEM_INIT_FAILED_ALT 189
#define TXT_FILESYSTEM_INIT_SUCCESS_ALT 190
#define TXT_WIFI_CONFIG_LOAD_SUCCESS 191
#define TXT_WIFI_CONNECT_SUCCESS_ALT 192
#define TXT_WIFI_CONNECT_FAILED 193
#define TXT_NO_VALID_WIFI_CONFIG_ALT 194
#define TXT_FILESYSTEM_UPDATE_REQUEST_ALT 195
#define TXT_FILESYSTEM_IMAGE_FOUND_ALT 196
#define TXT_FILESYSTEM_UPDATE_APPLY_ALT 197
#define TXT_FILESYSTEM_IMAGE_NOT_FOUND 198
#define TXT_START_PID_AUTOTUNE_PROCESS 199
#define TXT_ENSURE_OVEN_EMPTY 200
#define TXT_WAITING_FOR_TEMP_STABILIZE 201
#define TXT_FINDING_CRITICAL_GAIN_ALT 202
#define TXT_INCREASING_KP 203
#define TXT_SUSTAINED_OSCILLATION_DETECTED 204
#define TXT_OSCILLATION_PERIOD 205
#define TXT_SECONDS 206
#define TXT_PID_AUTOTUNE_COMPLETE 207
#define TXT_RECOMMENDED_PARAMS_ALT 208
#define TXT_NEW_PARAMS_SAVED_TO_EEPROM 209
#define TXT_NO_SUSTAINED_OSCILLATION 210
#define TXT_PID_AUTOTUNE_FINISHED 211

// 新增缺失的宏定义
#define TXT_SENSOR_DATA_INVALID 567
#define TXT_SENSOR_COMM_FAILURE 586
#define TXT_TEMP_READ 588
#define TXT_TEMP_OUT_OF_RANGE 589
#define TXT_SENSOR_STATUS_ABNORMAL 590
#define TXT_SENSOR_STATUS_FAILURE 591
// 修复重复定义问题
// TXT_SENSOR_COMM_ERROR 已在前面定义 (值为350)
// TXT_TEMP_CALIBRATION_COMPLETE 已在前面定义 (值为593)
// TXT_ACTUAL_TEMP 已在前面定义 (值为594)
// TXT_MEASURED_TEMP 已在前面定义 (值为595)
// TXT_CALIBRATION_SAVED 已在前面定义 (值为596)
// TXT_CAPTIVE_PORTAL_START 已在前面定义 (值为597)
// TXT_AP_SSID 已在前面定义 (值为598)
// TXT_AP_IP 已在前面定义 (值为599)
// TXT_CAPTIVE_PORTAL_STARTED 已在前面定义 (值为600)
#define TXT_CAPTIVE_PORTAL_TIMEOUT 601

// 新增的HTML和JavaScript文本ID
#define TXT_SCANNING_WIFI_NETWORKS_JS 274
#define TXT_PLEASE_SELECT_WIFI_NETWORK_JS 275
#define TXT_NO_AVAILABLE_WIFI_NETWORKS_JS 276
#define TXT_SCAN_WIFI_FAILED_JS 277
#define TXT_SCAN_FAILED_PLEASE_RETRY_JS 278
#define TXT_WARNING_RESET_CONFIRMATION_JS 279
#define TXT_RESETTING_JS 280
#define TXT_RESET_SUCCESS_RESTARTING_JS 281
#define TXT_FACTORY_RESET_FAILED_JS 282
#define TXT_DEVICE_ID_LABEL 283
#define TXT_FIRMWARE_VERSION_LABEL_JS 284
#define TXT_CURRENT_TEMPERATURE_JS 285
#define TXT_CLICK_TO_SEARCH_WIFI_JS 286
#define TXT_SELECT_WIFI_NETWORK_JS 287
#define TXT_ENTER_WIFI_PASSWORD_JS 288
#define TXT_CONNECT_WIFI_JS 289
#define TXT_UPLOAD_PROGRESS_JS 290
#define TXT_SMART_OVEN_CONTROLLER_WIFI_CONFIG_PAGE_JS 291
#define TXT_WIFI_NETWORK_SETTINGS_JS 292
#define TXT_IMPORTANT_NOTE_FIRMWARE_UPGRADE_JS 293
#define TXT_IMPORTANT_NOTE_FILESYSTEM_UPDATE_JS 294
#define TXT_SELECT_FIRMWARE_FILE_JS 295
#define TXT_START_FIRMWARE_UPGRADE_JS 296
#define TXT_SELECT_FILESYSTEM_IMAGE_JS 297
#define TXT_START_FILESYSTEM_UPDATE_JS 298
#define TXT_BACK_TO_SELECTION 299
#define TXT_SELECT_UPGRADE_METHOD 300
#define TXT_FIRMWARE_UPGRADE_OPTION 301
#define TXT_FILESYSTEM_UPDATE_OPTION 302
#define TXT_UPDATE_DEVICE_MAIN_PROGRAM 303
#define TXT_UPDATE_FILESYSTEM_IMAGE 304
#define TXT_DEVICE_WILL_RESTART_AUTOMATICALLY 305
#define TXT_ENSURE_STABLE_POWER_SUPPLY 306
#define TXT_FIRMWARE_UPGRADE_SUCCESS_JS_MSG 307
#define TXT_UPDATE_FAILED_JS_MSG 308
#define TXT_FILESYSTEM_UPDATE_SUCCESS_JS_MSG 309
#define TXT_DEVICE_STATUS_LABEL 310
#define TXT_UPTIME 311
#define TXT_MINUTES 312
#define TXT_FREE_MEMORY 313
#define TXT_WIFI_STATUS_LABEL_JS 314
#define TXT_WIFI_CONNECTED_JS 315
#define TXT_WIFI_DISCONNECTED_JS 316
#define TXT_SYSTEM_CORE_LABEL 317
#define TXT_INTERFACE_AND_DATA_LABEL 318
#define TXT_SCANNING_COMPLETED_JS 319
#define TXT_NETWORKS_JS 320
#define TXT_FACTORY_RESET_JS 321

// 翻译宏定义
#define TR(id) getText((int)id)

// 文本获取函数
const char* getText(int textId);

#endif