#include "lang.h"
#include <Arduino.h>

// Current language setting, default to Chinese
int currentLanguage = LANGUAGE_CHINESE;

// Chinese text array
const char* chineseText[] = {
    "WiFi配置保存成功",
    "设备将在5秒后重启并尝试连接WiFi网络...",
    "WiFi配置保存失败",
    "缺少必要的参数",
    "PID参数已保存",
    "配置保存失败",
    "PID控制已启用",
    "PID控制已禁用",
    "收到串口命令: ",
    "=== 设备状态 ===",
    "温度: ",
    "目标温度: ",
    "加热状态: ",
    "开启",
    "关闭",
    "工作模式: ",
    "烤箱模式",
    "烤面包机模式",
    "WiFi状态: ",
    "已连接",
    "未连接",
    "PID控制: ",
    "启用",
    "禁用",
    "Kp: ",
    "Ki: ",
    "Kd: ",
    "IP地址: ",
    "执行设备重启...",
    "目标温度已设置为: ",
    "加热已开启",
    "加热已关闭",
    "温度校准模式",
    "请使用网页界面进行温度校准",
    "Kp已设置为: ",
    "Ki已设置为: ",
    "Kd已设置为: ",
    "配置已保存到EEPROM",
    "配置加载失败",
    "已重置为默认配置",
    "启动PID自动调优程序...",
    "未知命令，可用命令: status, reset, set_temp [温度], heat_on, heat_off, calibrate, pid_on, pid_off, set_kp [值], set_ki [值], set_kd [值], save_config, load_config, reset_config, autotune_pid",
    "文件系统初始化失败，HTML文件服务将不可用",
    "Filesystem initialized successfully",
    "WiFi configuration loaded successfully, attempting to connect to network...",
    "SSID：",
    "WiFi连接成功，设备进入正常模式",
    "WiFi连接失败，启动Captive Portal配网模式",
    "未找到有效WiFi配置，启动Captive Portal配网模式",
    "检测到文件系统更新请求，开始处理...",
    "找到文件系统镜像，准备更新...",
    "文件系统更新将在本次启动中生效",
    "警告：未找到文件系统镜像文件，但检测到更新标志",
    "烘焙完成提示结束",
    "开始PID自动调优...",
    "请确保烤箱为空并且在安全环境下操作",
    "目标温度设置为: ",
    "等待温度稳定...",
    "当前温度: ",
    "开始寻找临界增益...",
    "逐步增加Kp直到出现持续振荡...",
    "检测到持续振荡! 临界增益 Ku = ",
    "PID自动调优完成!",
    "推荐参数: Kp = ",
    ", Ki = ",
    ", Kd = ",
    "新参数已保存到EEPROM",
    "未能检测到持续振荡，请手动调整参数",
    "PID自动调优过程结束",
    
    // 新增的中文文本
    "WiFi连接超时处理：最多尝试10秒，期间每500ms检查一次连接状态",
    "检查WiFi连接结果",
    "设备发现协议处理",
    "OTA更新设置",
    "智能烤箱设备WiFi配置页面",
    "WiFi网络连接设置",
    "Please select WiFi network",
    "未找到可用的WiFi网络",
    "扫描WiFi网络失败",
    "Warning: This operation will reset all settings and clear WiFi configuration! Are you sure you want to continue?",
    "正在重置...",
    "重置成功...设备正在重启",
    "工厂重置失败: ",
    "智能烤箱控制器 - WiFi配置页面",
    "WiFi网络名称",
    "WiFi密码",
    "请输入WiFi密码",
    "点击搜索WiFi网络",
    "连接WiFi",
    "扫描WiFi网络失败",
    "扫描失败，请重试",
    "智能烤箱控制器 - OTA升级",
    "固件升级 (.bin 文件)",
    "System Core",
    "Update device main program with feature improvements and bug fixes. Device will automatically restart after upgrade.",
    "文件系统更新 (.bin 文件)",
    "Interface and Data",
    "Update complete filesystem image including all HTML, JS, CSS interface files.",
    "重要提示：固件升级将重启设备，请确保电源稳定。",
    "选择固件文件 (.bin):",
    "开始升级固件",
    "上传进度: ",
    "固件升级成功！设备将在3秒后重启...",
    "升级失败：",
    "文件系统更新",
    "Important: Filesystem update will overwrite all existing interface files. Please ensure you are using the correct .bin image file.",
    "选择文件系统镜像 (.bin):",
    "开始更新文件系统",
    "文件系统更新成功！设备将在3秒后重启...",
    "更新失败：",
    "设备将在3秒后重启",
    "✅ 固件升级成功！设备将在3秒后重启...",
    "❌ 升级失败：",
    "✅ 文件系统更新成功！设备将在3秒后重启...",
    "❌ 更新失败：",
    "已登出",
    "密码修改成功",
    "密码长度至少需要8位",
    "缺少新密码参数",
    "温度校准参数已重置",
    "文件系统.bin更新处理函数",
    "重启设备应用文件系统更新...",
    "文件上传处理函数 - 重新设计进度计算逻辑",
    "EEPROM read failed, retrying ",
    "Warning: Temperature calibration offset out of range, reset to 0",
    "Warning: Temperature calibration scale out of range, reset to 1",
    "读取尝试"
    "不支持的文件类型: ",
    "===== 文件上传开始 =====",
    "文件名: ",
    "已启动SSE响应流",
    "响应头信息 - Content-Type: ",
    "发送进度事件: ",
    "块: ",
    "写入: ",
    "累计: ",
    "预估大小: ",
    "进度: ",
    "===== 文件上传完成 =====",
    "文件: ",
    "大小: ",
    "总块数: ",
    "文件系统镜像上传完成，等待更新",
    "警告：文件验证失败，文件不存在",
    "固件文件上传完成，等待OTA升级",
    "文件上传被取消，已删除不完整文件",
    "设置静态文件服务（所有模式下都需要）",
    "配置保存成功提示音 - 短鸣提示",
    "烘焙开始提示音 - 长鸣提示",
    "烘焙完成提示音 - 连续短鸣",
    "错误提示音 - 急促短鸣",
    "收到TCP命令: ",
    "Web服务器处理函数",
    "扫描可用的WiFi网络",
    "WiFi配置保存成功",
    "设备将在5秒后重启",
    "如果连接成功，请使用浏览器访问设备IP地址",
    "如果连接失败，设备将在3分钟后重新启动配网模式",
    "WiFi配置保存失败",
    "参数不完整",
    "PID控制API处理函数",
    "返回当前PID参数",
    "设置PID参数",
    "PID参数已保存",
    "配置保存失败",
    "PID已启用",
    "PID已禁用",
    "串口命令处理函数",
    "收到串口命令: ",
    "设备状态信息",
    "温度: ",
    "目标温度: ",
    "加热状态: ",
    "工作模式: ",
    "烤箱模式",
    "面包机模式",
    "WiFi状态: ",
    "WiFi已连接",
    "WiFi未连接",
    "PID控制: ",
    "已启用",
    "已禁用",
    "执行设备重启...",
    "加热已开启",
    "加热已关闭",
    "温度校准模式",
    "请使用网页界面进行温度校准",
    "PID控制已启用",
    "PID控制已禁用",
    "配置已保存到EEPROM",
    "配置保存失败",
    "配置从EEPROM加载成功",
    "配置加载失败",
    "已重置为默认配置",
    "启动PID自动调优",
    
    // 智能烤箱控制器固件注释文本
    "智能烤箱控制器固件",
    "固件版本",
    "主要功能",
    "硬件支持",
    "硬件引脚定义",
    "系统配置参数",
    "全局对象定义",
    "系统运行状态变量",
    "硬件状态监控",
    "设备信息定义",
    "WiFi配置参数",
    "captive portal模式配置",
    "文件系统状态",
    "温度控制变量",
    "PID控制变量",
    "PID计算中间变量",
    "PWM控制变量",
    "网络通信配置",
    "温度校准参数配置",
    "设备发现配置",
    "LED状态控制与闪烁管理",
    "烘焙完成状态管理与提示控制",
    "EEPROM配置管理模块",
    "未知命令",
    "烘焙完成通知结束",
    "文件系统初始化失败",
    "文件系统初始化成功",
    "WiFi配置加载成功",
    "WiFi连接成功",
    "WiFi连接失败",
    "未找到有效的WiFi配置",
    "检测到文件系统更新请求",
    "找到文件系统镜像",
    "应用文件系统更新",
    "未找到文件系统镜像",
    "开始PID自动调优过程",
    "请确保烤箱为空",
    "等待温度稳定",
    "开始寻找临界增益",
    "逐步增加Kp直到出现持续振荡",
    "检测到持续振荡! 临界增益 Ku = ",
    "振荡周期 Tu = ",
    " 秒",
    "PID自动调优完成!",
    "推荐参数: ",
    "新参数已保存到EEPROM",
    "未能检测到持续振荡",
    "PID自动调优过程结束",
    
    // 新增的中文文本
    "EEPROM读取失败，重试 ",
    "警告：温度校准偏移量超出合理范围，重置为0",
    "警告：温度校准缩放系数超出合理范围，重置为1",
    "传感器通信错误: MAX6675未连接或读取失败",
    "原始数据: 0x",
    "使用保存的WiFi配置参数尝试连接网络",
    "WiFi连接状态: ",
    "IP地址: ",
    "连接耗时: ",
    "WiFi连接失败原因: ",
    "WiFi连接状态: ",
    "IP地址: ",
    "失败原因: ",
    "扫描WiFi网络中...",
    "Please select WiFi network",
    "未找到可用的WiFi网络",
    "扫描WiFi网络失败",
    "警告：此操作将重置所有设置并清除WiFi配置！确定要继续吗？",
    "正在重置...",
    "重置成功...设备正在重启",
    "工厂重置失败: ",
    "智能烤箱控制器 - WiFi配置页面",
    "WiFi网络连接设置",
    "设备ID:",
    "固件版本:",
    "当前温度: ",
    "点击搜索WiFi网络",
    "WiFi网络名称",
    "WiFi密码",
    "请输入WiFi密码",
    "连接WiFi",
    "上传进度: ",
    "收到TCP命令: ",
    "收到串口命令: ",
    "温度: ",
    "目标温度: ",
    "目标温度已设置为: ",
    "Kp已设置为: ",
    "Ki已设置为: ",
    "Kd已设置为: ",
    "PID控制 - 温度: ",
    "目标: ",
    "误差: ",
    "PID输出: ",
    
    // 新增的HTML和JavaScript中文文本
    "扫描WiFi网络中...",
    "请选择WiFi网络",
    "未找到可用的WiFi网络",
    "扫描WiFi网络失败",
    "扫描失败，请重试",
    "警告：此操作将重置所有设置并清除WiFi配置！确定要继续吗？",
    "正在重置...",
    "重置成功...设备正在重启",
    "工厂重置失败: ",
    "设备ID:",
    "固件版本:",
    "当前温度: ",
    "点击搜索WiFi网络",
    "WiFi网络名称",
    "WiFi密码",
    "请输入WiFi密码",
    "连接WiFi",
    "上传进度: ",
    "智能烤箱控制器 - WiFi配置页面",
    "WiFi网络连接设置",
    "重要提示：固件升级将重启设备，请确保电源稳定。",
    "重要提示：文件系统更新将覆盖所有现有界面文件，请确保使用正确的.bin镜像文件。",
    "选择固件文件 (.bin):",
    "开始升级固件",
    "选择文件系统镜像 (.bin):",
    "开始更新文件系统",
    "⬅️ 返回选择",
    "请选择合适的升级方式:",
    "固件升级 (.bin 文件)",
    "文件系统更新 (.bin 文件)",
    "更新设备主程序，包含功能改进和错误修复。",
    "更新完整的文件系统镜像，包含所有HTML、JS、CSS等界面文件。",
    "设备将在升级后自动重启。",
    "请确保电源稳定。",
    "✅ 固件升级成功！设备将在3秒后重启...",
    "❌ 升级失败：",
    "✅ 文件系统更新成功！设备将在3秒后重启...",
    "❌ 更新失败：",
    "已登出",
    "密码修改成功",
    "密码长度至少需要8个字符",
    "缺少新密码参数",
    "温度校准参数已重置",
    "文件系统.bin更新处理函数",
    "重启设备应用文件系统更新...",
    "文件上传处理函数 - 重新设计进度计算逻辑",
    "不支持的文件类型: ",
    "===== 文件上传开始 =====",
    "文件名: ",
    "已启动SSE响应流",
    "响应头信息 - Content-Type: ",
    "发送进度事件: "
    "块: ",
    "写入: ",
    "累计: "
    "预估大小: ",
    "进度: ",
    "===== 文件上传完成 ====="
    "文件: ",
    "大小: ",
    "总块数: "
    "文件系统镜像上传完成，等待更新",
    "警告：文件验证失败，文件不存在",
    "固件文件上传完成，等待OTA升级"
    "文件上传被取消，不完整文件已删除",
    "设置静态文件服务（所有模式下都需要）",
    "配置保存成功提示音 - 短鸣提示"
    "烘焙开始提示音 - 长鸣提示",
    "烘焙完成提示音 - 连续短鸣",
    "错误提示音 - 急促短鸣"
    "收到TCP命令: ",
    "Web服务器处理函数",
    "扫描可用WiFi网络"
    "WiFi配置保存成功",
    "设备将在5秒后重启",
    "如果连接成功，请使用浏览器访问设备IP地址"
    "如果连接失败，设备将在3分钟后重新启动配网模式",
    "WiFi配置保存失败",
    "参数不完整"
    "PID控制API处理函数",
    "返回当前PID参数",
    "设置PID参数"
    "PID参数已保存",
    "配置保存失败",
    "PID已启用"
    "PID已禁用",
    "串口命令处理函数",
    "收到串口命令: "
    "设备状态信息",
    "温度: ",
    "目标温度: "
    "加热状态: ",
    "工作模式: ",
    "烤箱模式"
    "烤面包机模式",
    "WiFi状态: ",
    "WiFi已连接"
    "WiFi未连接",
    "PID控制: ",
    "已启用"
    "已禁用",
    "重启设备中...",
    "加热已开启"
    "加热已关闭",
    "温度校准模式",
    "请使用网页界面进行温度校准"
    "PID控制已启用",
    "PID控制已禁用",
    "配置已保存到EEPROM"
    "配置保存失败",
    "配置从EEPROM加载成功",
    "配置加载失败"
    "重置为默认配置",
    "启动PID自动调优",
    
    // 智能烤箱控制器固件注释文本
    "智能烤箱控制器固件"
    "固件版本",
    "主要功能",
    "硬件支持"
    "硬件引脚定义",
    "系统配置参数",
    "全局对象定义"
    "系统运行状态变量",
    "硬件状态监控",
    "设备信息定义"
    "WiFi配置参数",
    "Captive Portal模式配置",
    "文件系统状态"
    "温度控制变量",
    "PID控制变量",
    "PID计算中间变量"
    "PWM控制变量",
    "网络通信配置",
    "温度校准参数配置"
    "设备发现配置",
    "LED状态控制与闪烁管理",
    "烘焙完成状态管理与提示控制"
    "EEPROM配置管理模块",
    
    "未知命令",
    "烘焙完成提示已结束",
    "文件系统初始化失败",
    "文件系统初始化成功",
    "WiFi配置加载成功",
    "WiFi连接成功",
    "WiFi连接失败",
    "未找到有效的WiFi配置",
    "检测到文件系统更新请求",
    "找到文件系统镜像",
    "应用文件系统更新",
    "未找到文件系统镜像",
    "启动PID自动调优过程",
    "请确保烤箱为空",
    "等待温度稳定",
    "开始寻找临界增益",
    "逐渐增加Kp直至出现持续振荡",
    "检测到持续振荡！临界增益 Ku = ",
    "振荡周期 Tu = ",
    " 秒",
    "PID自动调优完成！"
    "推荐参数：",
    "新参数已保存到EEPROM"
    "无法检测到持续振荡",
    "PID自动调优过程已结束"
    
    // Newly added English texts
    "EEPROM读取失败，重试 ",
    "警告：温度校准偏移量超出合理范围，重置为0",
    "警告：温度校准缩放系数超出合理范围，重置为1"
    "Sensor communication error: MAX6675 not connected or read failed",
    "Raw data: 0x"
    "使用保存的WiFi配置参数尝试网络连接",
    "WiFi连接状态："
    "IP Address: ",
    "连接时间："
    "WiFi连接失败原因：",
    "WiFi连接状态："
    "IP地址：",
    "失败原因："
    "扫描WiFi网络中...",
    "请选择WiFi网络"
    "No available WiFi networks found",
    "WiFi network scan failed"
    "警告：此操作将重置所有设置并清除WiFi配置！确定要继续吗？",
    "正在重置..."
    "重置成功... 设备正在重启",
    "恢复出厂设置失败："
    "智能烤箱控制器 - WiFi配置页面",
    "WiFi网络连接设置"
    "设备ID：",
    "固件版本："
    "当前温度：",
    "点击搜索WiFi网络"
    "WiFi网络名称",
    "WiFi密码"
    "请输入WiFi密码",
    "连接WiFi"
    "上传进度：",
    "收到TCP命令："
    "收到串口命令：",
    "温度："
    "目标温度：",
    "目标温度已设置为："
    "Kp已设置为：",
    "Ki已设置为："
    "Kd已设置为：",
    "PID控制 - 温度："
    "目标：",
    "误差："
    "PID输出："
    
    // New HTML and JavaScript English texts
    "扫描WiFi网络中...",
    "请选择WiFi网络",
    "No available WiFi networks found"
    "WiFi network scan failed",
    "扫描失败，请重试"
    "警告：此操作将重置所有设置并清除WiFi配置！确定要继续吗？",
    "正在重置..."
    "重置成功... 设备正在重启",
    "恢复出厂设置失败："
    "设备ID：",
    "固件版本："
    "当前温度：",
    "点击搜索WiFi网络"
    "WiFi网络名称",
    "WiFi密码"
    "请输入WiFi密码",
    "连接WiFi"
    "上传进度：",
    "智能烤箱控制器 - WiFi配置页面"
    "WiFi网络连接设置",
    "Important: Firmware upgrade will restart the device. Ensure stable power supply."
    "重要提示：文件系统更新将覆盖所有现有界面文件，请确保使用正确的.bin镜像文件。"
    "Select firmware file (.bin):"
    "开始固件升级",
    "选择文件系统镜像 (.bin)："
    "开始文件系统更新",
    "⬅️ 返回选择"
    "请选择升级方式：",
    "固件升级 (.bin文件)"
    "文件系统更新 (.bin文件)",
    "更新设备主程序，包括功能改进和错误修复。"
    "更新完整文件系统镜像，包括所有HTML、JS、CSS和其他界面文件。"
    "设备将在升级后自动重启。"
    "请确保稳定供电。"
    "✅ 固件升级成功！设备将在3秒后重启..."
    "❌ 升级失败："
    "✅ 文件系统更新成功！设备将在3秒后重启..."
    "设备状态信息",
    "运行时间："
    "分钟",
    "可用内存："
    "WiFi状态："
    "WiFi已连接"
    "WiFi未连接",
    "系统核心"
    "界面与数据",
    "扫描完成"
    "个网络",
    "恢复出厂设置"
    
    // Newly added English error messages
    "Invalid SSID",
    "Password length exceeds 63 characters",
    "EEPROM save failed, retrying",
    "PID Enabled:",
    "Enabled",
    "Disabled",
    "EEPROM read failed, retrying ",
    "Warning: Temperature calibration offset out of range, reset to 0",
    "Warning: Temperature calibration scale out of range, reset to 1",
    "Read attempt "
    "temp_calibration_offset_warn",
    "temp_calibration_scale_warn",
    "read_attempt",
    "Configuration saved successfully",
    "Sensor data invalid",
    "EEPROM读取失败",
    "Loading configuration",
    "Configuration signature:",
    "Configuration SSID:",
    "Password length:",
    "Temperature offset:",
    "Temperature scaling:",
    "PID Kp:",
    "PID enabled:",
    "Enabled",
    "Disabled",
    "Configuration loaded successfully",
    "Configuration signature invalid",
    "Default configuration loaded",
    "EEPROM保存失败",
    "Read attempts",
    
    // Newly added English texts for sensor, temperature, calibration and captive portal
    "Sensor communication failure",
    "Sensor read failure",
    "Temperature read: ",
    "Temperature out of valid range (-50.0°C to 400.0°C)",
    "Sensor status abnormal",
    "Sensor status fault",
    "Sensor communication error",
    "Temperature calibration complete",
    "Actual temperature: ",
    "Measured temperature: ",
    "Calibration parameters saved",
    "Starting Captive Portal service",
    "AP SSID: ",
    "AP IP Address: ",
    "Captive Portal service started",

    // PID自动调优确认机制相关文本
    "PID自动调优需要确认。请在30秒内发送CONFIRM_AUTOTUNE命令。",
    "PID自动调优已确认。正在启动过程...",
    "PID自动调优确认超时。过程已取消。",
    "PID自动调优已在进行中。",
    "无法在当前温度下启动PID自动调优。为安全起见，温度必须低于100°C。"
};

// English text array
const char* englishText[] = {
    "WiFi configuration saved successfully",
    "Device will restart in 5 seconds and attempt to connect to WiFi network...",
    "WiFi configuration save failed",
    "Missing required parameters",
    "PID parameters saved",
    "Configuration save failed",
    "PID control enabled",
    "PID control disabled",
    "Received serial command: ",
    "=== Device Status ===",
    "Temperature: ",
    "Target Temperature: ",
    "Heating Status: ",
    "ON",
    "OFF",
    "Work Mode: ",
    "Oven Mode",
    "Toaster Mode",
    "WiFi Status: ",
    "Connected",
    "Disconnected",
    "PID Control: ",
    "Enabled",
    "Disabled",
    "Kp: ",
    "Ki: ",
    "Kd: ",
    "IP地址：",
    "Restarting device...",
    "Target temperature set to: ",
    "Heating turned ON",
    "Heating turned OFF",
    "Temperature calibration mode",
    "Please use web interface for temperature calibration",
    "Kp set to: ",
    "Ki set to: ",
    "Kd set to: ",
    "Configuration saved to EEPROM",
    "Configuration load failed",
    "Reset to default configuration",
    "Starting PID auto-tuning...",
    "Unknown command, available commands: status, reset, set_temp [temp], heat_on, heat_off, calibrate, pid_on, pid_off, set_kp [value], set_ki [value], set_kd [value], save_config, load_config, reset_config, autotune_pid",
    "Filesystem initialization failed, HTML file service will be unavailable",
    "文件系统初始化成功"
    "WiFi configuration loaded successfully, attempting to connect to network...",
    "SSID: ",
    "WiFi connection successful, device entering normal mode",
    "WiFi connection failed, starting Captive Portal configuration mode",
    "No valid WiFi configuration found, starting Captive Portal configuration mode",
    "Filesystem update request detected, starting processing...",
    "Filesystem image found, preparing for update...",
    "Filesystem update will take effect on next boot",
    "Warning: Filesystem image file not found, but update flag detected",
    "Baking complete notification ended",
    "Starting PID auto-tuning...",
    "Please ensure oven is empty and operate in safe environment",
    "Target temperature set to: ",
    "Waiting for temperature to stabilize...",
    "Current temperature: ",
    "Starting to find critical gain...",
    "Gradually increasing Kp until sustained oscillation occurs...",
    "Sustained oscillation detected! Critical gain Ku = ",
    "PID auto-tuning complete!",
    "Recommended parameters: Kp = ",
    ", Ki = ",
    ", Kd = ",
    "New parameters saved to EEPROM",
    "Unable to detect sustained oscillation, please adjust parameters manually",
    "PID auto-tuning process ended",

    // Newly added English texts
    "WiFi connection timeout handling: maximum 10 seconds attempt, check connection status every 500ms",
    "Check WiFi connection result",
    "Device discovery protocol handling",
    "OTA update setup",
    "Smart Oven Device WiFi Configuration Page",
    "WiFi Network Connection Settings",
    "请选择WiFi网络"
    "未找到可用WiFi网络",
     "WiFi网络扫描失败",
    "警告：此操作将重置所有设置并清除WiFi配置！确定要继续吗？",
    "正在重置..."
    "重置成功... 设备正在重启",
    "恢复出厂设置失败："
    "智能烤箱控制器 - WiFi配置页面"
    "WiFi网络名称"
    "WiFi密码"
    "请输入WiFi密码"
    "点击搜索WiFi网络"
    "连接WiFi"
    "WiFi网络扫描失败"
    "扫描失败，请重试"
    "智能烤箱控制器 - OTA更新"
    "Firmware Upgrade (.bin file)",
    "系统核心"
    "Update device main program with feature improvements and bug fixes. Device will automatically restart after upgrade."
    "Filesystem Update (.bin file)",
    "界面与数据"
    "Update complete filesystem image including all HTML, JS, and CSS interface files."
    "重要提示：固件升级将重启设备，请确保稳定供电。"
    "选择固件文件 (.bin)："
    "开始固件升级"
    "上传进度："
    "固件升级成功！设备将在3秒后重启..."
    "升级失败："
    "文件系统更新"
    "重要提示：文件系统更新将覆盖所有现有界面文件，请确保使用正确的.bin镜像文件。"
    "选择文件系统镜像 (.bin)："
    "开始文件系统更新"
    "文件系统更新成功！设备将在3秒后重启..."
    "更新失败："
    "Device will restart in 3 seconds",
    "✅ Firmware upgrade successful! Device will restart in 3 seconds...",
    "❌ Upgrade failed: ",
    "✅ Filesystem update successful! Device will restart in 3 seconds...",
    "❌ Update failed: ",
    "已登出"
    "密码修改成功"
    "密码长度至少为8个字符"
    "缺少新密码参数"
    "温度校准参数已重置"
    "文件系统.bin更新处理函数"
    "正在重启设备以应用文件系统更新..."
    "文件上传处理函数 - 重新设计的进度计算逻辑"
    "不支持的文件类型："
    "===== 文件上传开始 ====="
    "文件名："
    "SSE响应流已启动"
    "响应头信息 - Content-Type："
    "正在发送进度事件："
    "块："
    "已写入："
    "累计："
    "估计大小："
    "进度："
    "===== 文件上传完成 ====="
    "文件："
    "大小："
    "总块数："
    "Filesystem image upload completed, waiting for update",
    "Warning: File validation failed, file does not exist",
    "Firmware file upload completed, waiting for OTA upgrade",
    "File upload cancelled, incomplete file deleted",
    "Setting up static file service (required in all modes)",
    "Configuration saved successfully beep - short beep notification",
    "Baking started beep - long beep notification",
    "Baking completed beep - continuous short beeps",
    "Error beep - urgent short beeps",
    "Received TCP command: ",
    "Web server handler function",
    "Scanning available WiFi networks",
    "WiFi configuration saved successfully",
    "Device will restart in 5 seconds",
    "If connected successfully, please use browser to access device IP address",
    "If connection fails, device will restart provisioning mode in 3 minutes",
    "WiFi configuration save failed",
    "Incomplete parameters",
    "PID control API handler function",
    "Return current PID parameters",
    "Set PID parameters",
    "PID parameters saved",
    "Configuration save failed",
    "PID enabled",
    "PID disabled",
    "Serial command handler function",
    "Received serial command: ",
    "Device status information",
    "Temperature: ",
    "Target Temperature: ",
    "Heating Status: ",
    "Work Mode: ",
    "Oven Mode",
    "Toaster Mode",
    "WiFi Status: ",
    "WiFi connected",
    "WiFi not connected",
    "PID Control: ",
    "Enabled",
    "Disabled",
    "Restarting device...",
    "Heating turned ON",
    "Heating turned OFF",
    "Temperature calibration mode",
    "Please use web interface for temperature calibration",
    "PID control enabled",
    "PID control disabled",
    "Configuration saved to EEPROM",
    "Configuration save failed",
    "Configuration loaded successfully from EEPROM",
    "Configuration load failed",
    "Reset to default configuration",
    "Starting PID auto-tuning",

    // Smart Oven Controller Firmware comment texts
    "Smart Oven Controller Firmware",
    "Firmware Version",
    "Main Features",
    "Hardware Support",
    "Hardware Pin Definitions",
    "System Configuration Parameters",
    "Global Object Definitions",
    "System Runtime Variables",
    "Hardware Status Monitoring",
    "Device Information Definition",
    "WiFi Configuration Parameters",
    "Captive Portal Mode Configuration",
    "File System Status",
    "Temperature Control Variables",
    "PID Control Variables",
    "PID Calculation Intermediate Variables",
    "PWM Control Variables",
    "Network Communication Configuration",
    "Temperature Calibration Parameter Configuration",
    "Device Discovery Configuration",
    "LED Status Control and Blink Management",
    "Baking Completion Status Management and Notification Control",
    "EEPROM Configuration Management Module",

    "Unknown command",
    "Baking complete notification ended",
    "文件系统初始化失败：",
    "Filesystem initialized successfully",
    "WiFi configuration loaded successfully",
    "WiFi connected successfully",
    "WiFi connection failed",
    "No valid WiFi configuration found",
    "Filesystem update request detected",
    "Filesystem image found",
    "Applying filesystem update",
    "Filesystem image not found",
    "Starting PID auto-tuning process",
    "Please ensure oven is empty",
    "Waiting for temperature to stabilize",
    "Starting to find critical gain",
    "Gradually increasing Kp until sustained oscillation occurs",
    "Sustained oscillation detected! Critical gain Ku = ",
    "Oscillation period Tu = ",
    " seconds",
    "PID auto-tuning complete!",
    "Recommended parameters: ",
    "New parameters saved to EEPROM",
    "Unable to detect sustained oscillation",
    "PID auto-tuning process ended",

    // Newly added English texts
    "EEPROM读取失败，重试 ",
    "警告：温度校准偏移量超出合理范围，重置为0",
    "警告：温度校准缩放系数超出合理范围，重置为1"
    "传感器通信错误：MAX6675未连接或读取失败",
    "原始数据：0x"
    "使用已保存的WiFi配置参数尝试网络连接",
     "WiFi连接状态：",
     "IP地址：",
    "连接时间："
    "WiFi连接失败原因："
    "WiFi连接状态："
    "IP地址：",
    "失败原因："
    "正在扫描WiFi网络...",
     "请选择WiFi网络",
    "未找到可用WiFi网络"
    "Scan WiFi networks failed",
    "Warning: This operation will reset all settings and clear WiFi configuration! Are you sure you want to continue?",
    "Resetting...",
    "Reset successful... Device is restarting",
    "Factory reset failed: ",
    "Smart Oven Controller - WiFi Configuration Page",
    "WiFi Network Connection Settings",
    "设备ID："
    "固件版本："
    "当前温度："
    "Click to search WiFi networks",
    "WiFi Network Name",
    "WiFi Password",
    "Please enter WiFi password",
    "Connect WiFi",
    "Upload progress: ",
    "Received TCP command: ",
    "Received serial command: ",
    "Temperature: ",
    "Target Temperature: ",
    "Target temperature set to: ",
    "Kp set to: ",
    "Ki set to: ",
    "Kd set to: ",
    "PID control - Temperature: ",
    "Target: ",
    "Error: ",
    "PID output: ",

    // New HTML and JavaScript English texts
    "正在扫描WiFi网络..."
    "Please select WiFi network",
    "No available WiFi networks found",
    "Scan WiFi networks failed",
    "Scan failed, please try again",
    "Warning: This operation will reset all settings and clear WiFi configuration! Are you sure you want to continue?",
    "Resetting...",
    "Reset successful... Device is restarting",
    "Factory reset failed: ",
    "Device ID:",
    "Firmware Version:",
    "Current Temperature: ",
    "Click to search WiFi networks",
    "WiFi Network Name",
    "WiFi Password",
    "Please enter WiFi password",
    "Connect WiFi",
    "Upload progress: ",
    "Smart Oven Controller - WiFi Configuration Page",
    "WiFi Network Connection Settings",
    "Important Note: Firmware upgrade will restart the device, please ensure stable power supply.",
    "Important Note: Filesystem update will overwrite all existing interface files, please ensure using correct .bin image file.",
    "Select firmware file (.bin):",
    "Start firmware upgrade",
    "Select filesystem image (.bin):",
    "Start filesystem update",
    "⬅️ 返回选择"
    "Please select upgrade method:",
    "Firmware Upgrade (.bin file)",
    "Filesystem Update (.bin file)",
    "Update device main program, including feature improvements and bug fixes.",
    "Update complete filesystem image, including all HTML, JS, CSS and other interface files.",
    "Device will automatically restart after upgrade.",
    "Please ensure stable power supply.",
    "✅ Firmware upgrade successful! Device will restart in 3 seconds...",
    "❌ Upgrade failed:",
    "✅ Filesystem update successful! Device will restart in 3 seconds...",
    "❌ Update failed:",
    "Logged out",
    "Password changed successfully",
    "Password must be at least 8 characters",
    "Missing new password parameter",
    "Temperature calibration parameters reset",
    "Filesystem .bin update handler function",
    "Restarting device to apply filesystem update...",
    "File upload handler function - redesigned progress calculation logic",
    "Unsupported file type: ",
    "===== File upload started =====",
    "Filename: ",
    "SSE response stream started",
    "Response header info - Content-Type: ",
    "Sending progress event: ",
    "Block: ",
    "Written: ",
    "Accumulated: ",
    "Estimated size: ",
    "Progress: ",
    "===== File upload completed =====",
    "File: ",
    "Size: ",
    "Total blocks: ",
    "Filesystem image upload completed, waiting for update",
    "Warning: File validation failed, file does not exist",
    "Firmware file upload completed, waiting for OTA upgrade",
    "File upload cancelled, incomplete file deleted",
    "Setting up static file service (required in all modes)",
    "Configuration saved successfully beep - short beep notification",
    "Baking started beep - long beep notification",
    "Baking completed beep - continuous short beeps",
    "Error beep - urgent short beeps",
    "Received TCP command: ",
    "Web server handler function",
    "Scanning available WiFi networks",
    "WiFi configuration saved successfully",
    "Device will restart in 5 seconds",
    "If connected successfully, please use browser to access device IP address",
    "If connection fails, device will restart provisioning mode in 3 minutes",
    "Failed to save WiFi configuration",
    "Incomplete parameters",
    "PID control API handler function",
    "Return current PID parameters",
    "Set PID parameters",
    "PID parameters saved",
    "Failed to save configuration",
    "PID enabled",
    "PID disabled",
    "Serial command handler function",
    "Received serial command: ",
    "Device status information",
    "Temperature: ",
    "Target Temperature: ",
    "Heating Status: ",
    "Work Mode: ",
    "Oven Mode",
    "Toaster Mode",
    "WiFi Status: ",
    "WiFi connected",
    "WiFi not connected",
    "PID Control: ",
    "Enabled",
    "Disabled",
    "Restarting device...",
    "Heating turned ON",
    "Heating turned OFF",
    "Temperature calibration mode",
    "Please use web interface for temperature calibration",
    "PID control enabled",
    "PID control disabled",
    "Configuration saved to EEPROM",
    "Failed to save configuration",
    "Configuration loaded successfully from EEPROM",
    "Failed to load configuration",
    "Reset to default configuration",
    "Starting PID auto-tuning",

    // Smart Oven Controller Firmware comment texts
    "Smart Oven Controller Firmware",
    "Firmware Version",
    "Main Features",
    "Hardware Support",
    "Hardware Pin Definitions",
    "System Configuration Parameters",
    "Global Object Definitions",
    "System Runtime Variables",
    "Hardware Status Monitoring",
    "Device Information Definition",
    "WiFi Configuration Parameters",
    "Captive Portal Mode Configuration",
    "File System Status",
    "Temperature Control Variables",
    "PID Control Variables",
    "PID Calculation Intermediate Variables",
    "PWM Control Variables",
    "Network Communication Configuration",
    "Temperature Calibration Parameter Configuration",
    "Device Discovery Configuration",
    "LED Status Control and Blink Management",
    "Baking Completion Status Management and Notification Control",
    "EEPROM Configuration Management Module",

    "Unknown command",
    "Baking complete notification ended",
    "Failed to initialize filesystem",
    "Filesystem initialized successfully",
    "WiFi configuration loaded successfully",
    "WiFi connected successfully",
    "WiFi connection failed",
    "No valid WiFi configuration found",
    "Filesystem update request detected",
    "Filesystem image found",
    "Applying filesystem update",
    "Filesystem image not found",
    "Starting PID auto-tuning process",
    "Please ensure oven is empty",
    "Waiting for temperature to stabilize",
    "Starting to find critical gain",
    "Gradually increasing Kp until sustained oscillation occurs",
    "Sustained oscillation detected! Critical gain Ku = ",
    "Oscillation period Tu = ",
    " seconds",
    "PID auto-tuning complete!",
    "Recommended parameters: ",
    "New parameters saved to EEPROM",
    "Unable to detect sustained oscillation",
    "PID auto-tuning process ended",

    // Newly added English texts for sensor, temperature, calibration and captive portal
    "Sensor communication failure",
    "Sensor read failure",
    "Temperature read: ",
    "Temperature out of valid range (-50.0°C to 400.0°C)",
    "Sensor status abnormal",
    "Sensor status fault",
    "Sensor communication error",
    "Temperature calibration complete",
    "Actual temperature: ",
    "Measured temperature: ",
    "Calibration parameters saved",
    "Starting Captive Portal service",
    "AP SSID: ",
    "AP IP Address: ",
    "Captive Portal service started",

    // Newly added English error messages
    "Invalid SSID",
    "Password length exceeds 63 characters",
    "EEPROM保存失败，重试",
    "PID已启用：",
    "启用",
    "禁用",
    "Configuration saved successfully",
    "Sensor data invalid",
    "EEPROM读取失败"
    "Loading configuration",
    "Configuration signature:",
    "Configuration SSID:",
    "Password length:",
    "Temperature offset:",
    "Temperature scaling:",
    "PID Kp:",
    "PID enabled:",
    "Enabled",
    "Disabled",
    "Configuration loaded successfully",
    "Configuration signature invalid",
    "Default configuration loaded",
    "EEPROM保存失败"
    "Read attempts",

    // Newly added English texts for device status
    "Device status information",
    "Uptime:",
    "minutes",
    "Free memory:",
    "WiFi status:",
    "WiFi connected",
    "WiFi not connected",
    "System core",
    "Interface and data",
    "Scanning completed",
    "networks",
    "Factory reset",

    // PID Auto-tuning confirmation texts
    "PID auto-tuning requires confirmation. Please send CONFIRM_AUTOTUNE command within 30 seconds.",
    "PID auto-tuning confirmed. Starting process...",
    "PID auto-tuning confirmation timeout. Process cancelled.",
    "PID auto-tuning already in progress.",
    "Cannot start PID auto-tuning at current temperature. Temperature must be below 100°C for safety."
};

// Set language
void setLanguage(int lang) {
    if (lang == LANGUAGE_CHINESE || lang == LANGUAGE_ENGLISH) {
        currentLanguage = lang;
    }
}

// Get text by ID
const char* getText(int textId) {
    if (currentLanguage == LANGUAGE_CHINESE) {
        return chineseText[textId];
    } else {
        return englishText[textId];
    }
}